### ISSUE TITLE
[canRename] error: could not find identifier to rename

### ISSUE THREAD

**Issue by Jarrio** [HaxeCheckstyle/haxe-rename#11]
When trying to rename a local variable, I get the following error: "could not find identifier to rename".
Structure:
```hx
enum Foo {
	Value(data: String);
	Option(value:String, callback: Foo -> Void);
}

var other = 43; //works here
var e = Foo.Option('something', (resp) -> {
	resp.extract(Value(data) => {
		var x = 4; //fails here
	})
});
```
May have to do with the expression macro

https://github.com/user-attachments/assets/3b00c63b-e21d-496d-afd4-307dd4ca1ea8

**Comment by AlexHaxe** [comment]
thanks!
