### ISSUE TITLE
Rename.js crashes on string interpolation

### ISSUE THREAD

**Issue by dubspeed** [HaxeCheckstyle/haxe-rename#6]
👋 Hello,

this code below crashes rename.js parsing:

```haxe

package src;

abstract TestCrash(String) to String {
	public static inline function fail(data:Dynamic):TestCrash {
		return cast '${data.a}_${data.b}_${data.c}_${false}';
	}
}
```

**Comment by AlexHaxe** [comment]
the crash originates from a tokentree issue, where parsing `false` results in a `no more tokens` exception. so as soon as I fix tokentree, it should no longer crash haxe-rename's parser.
